[project]
name = "dataset-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "json-repair>=0.46.0",
    "langchain-openai>=0.3.18",
    "langgraph>=0.4.7",
    "loguru>=0.7.3",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "pathlib>=1.0.1",
    "playwright>=1.53.0",
    "pytest-playwright>=0.7.0",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "seaborn>=0.13.2",
    "uvicorn>=0.34.2",
]
[tool.uv]
index-url = "https://mirrors.aliyun.com/pypi/simple/"
